/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocomoJava;
import java.awt.Color;
import java.awt.DefaultFocusTraversalPolicy;
import java.text.DecimalFormat;

/**
 *
 * @author shriraksharao
 */
public class EAF_EarlyDesign extends javax.swing.JFrame {
            final int EAF_PERS  = 0;
	    final int EAF_RCPX  = 1;
	    final int EAF_PDIF  = 2;
	    final int EAF_PREX  = 3;
	    final int EAF_FCIL  = 4;
	    final int EAF_RUSE  = 5;
	    final int COST_DRIVER_COUNT = 6;
            CocomoDashboard cocoDashearly;
	    private String[] eafRatingearly;
	    private static DecimalFormat df2 = new DecimalFormat(".##");
	    private double netEafearly;
	    private double pers, rcpx, pdif, prex,fcil, ruse;
	    public static boolean isFile = false;

    /**
     * Creates new form EAF_EarlyDesign
     */
    public EAF_EarlyDesign(java.awt.Frame parent, boolean modal, String[] eafRatingearly) {
//        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.cocoDashearly = (CocomoDashboard) parent;
	netEafearly = 1.00;
	this.eafRatingearly = eafRatingearly;
	pers=rcpx=pdif=prex=fcil=ruse= 1.00;
        initEafLevelEarly();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Okbutton = new javax.swing.JButton();
        Cancelbutton = new javax.swing.JButton();
        perscombo = new javax.swing.JComboBox<>();
        rcpxcombo = new javax.swing.JComboBox<>();
        pdifcombo = new javax.swing.JComboBox<>();
        prexcombo = new javax.swing.JComboBox<>();
        fcilcombo = new javax.swing.JComboBox<>();
        rusecombo = new javax.swing.JComboBox<>();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setTitle("EAF_EARLY_DESIGN");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EAF_EARLYDESIGN");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("PERS");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("RCPX");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("PDIF");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("PREX");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("FCIL");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("RUSE");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("Schedule also contribute to EAF");

        Okbutton.setBackground(new java.awt.Color(102, 204, 255));
        Okbutton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Okbutton.setText("OK");
        Okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkbuttonActionPerformed(evt);
            }
        });

        Cancelbutton.setBackground(new java.awt.Color(102, 204, 255));
        Cancelbutton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Cancelbutton.setText("Cancel");
        Cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbuttonActionPerformed(evt);
            }
        });

        perscombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "XLOW", "VLOW", "LOW", "HIGH", "VHIGH", "XHIGH" }));
        perscombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perscomboActionPerformed(evt);
            }
        });

        rcpxcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "XLOW", "VLOW", "LOW", "HIGH", "VHIGH", "XHIGH", " " }));
        rcpxcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcpxcomboActionPerformed(evt);
            }
        });

        pdifcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "LOW", "HIGH", "VHIGH", "XHIGH" }));
        pdifcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdifcomboActionPerformed(evt);
            }
        });

        prexcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "XLOW", "VLOW", "LOW", "HIGH", "VHIGH", "XHIGH" }));
        prexcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prexcomboActionPerformed(evt);
            }
        });

        fcilcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "XLOW", "VLOW", "LOW", "HIGH", "VHIGH", "XHIGH" }));
        fcilcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcilcomboActionPerformed(evt);
            }
        });

        rusecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "LOW", "HIGH", "VHIGH", "XHIGH" }));
        rusecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rusecomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prexcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perscombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pdifcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rusecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel6))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addComponent(rcpxcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fcilcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Okbutton)
                                .addGap(56, 56, 56)
                                .addComponent(Cancelbutton))
                            .addComponent(jLabel7))))
                .addGap(29, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdifcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcpxcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perscombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Okbutton)
                            .addComponent(Cancelbutton))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prexcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fcilcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rusecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)))
                .addComponent(jLabel7)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkbuttonActionPerformed
        // TODO add your handling code here:
                getEAFSettingValues();
	        calculateEaf();
	        eafRatingearly[EAF_PERS]  = perscombo.getSelectedItem().toString();
	        eafRatingearly[EAF_RCPX]  = rcpxcombo.getSelectedItem().toString();
	        eafRatingearly[EAF_PDIF]  = pdifcombo.getSelectedItem().toString();
	        eafRatingearly[EAF_PREX] = prexcombo.getSelectedItem().toString();
	        eafRatingearly[EAF_FCIL] = fcilcombo.getSelectedItem().toString();
	        eafRatingearly[EAF_RUSE]  = rusecombo.getSelectedItem().toString();
	        
	        this.cocoDashearly.setEafearly(String.valueOf(df2.format(netEafearly)), eafRatingearly);
	        this.setVisible(false);
    }//GEN-LAST:event_OkbuttonActionPerformed

    private void CancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbuttonActionPerformed
        // TODO add your handling code here:
        initEafLevelEarly();
        this.dispose();
    }//GEN-LAST:event_CancelbuttonActionPerformed

    private void perscomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perscomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perscomboActionPerformed

    private void rcpxcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcpxcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcpxcomboActionPerformed

    private void pdifcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdifcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdifcomboActionPerformed

    private void prexcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prexcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prexcomboActionPerformed

    private void fcilcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcilcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcilcomboActionPerformed

    private void rusecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rusecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rusecomboActionPerformed
    
    private void getEAFSettingValues(){
        pers = EAFDefault_EarlyDesign.pers[perscombo.getSelectedIndex()];
        rcpx = EAFDefault_EarlyDesign.rcpx[rcpxcombo.getSelectedIndex()];
        pdif = EAFDefault_EarlyDesign.pdif[pdifcombo.getSelectedIndex()];
        prex = EAFDefault_EarlyDesign.prex[prexcombo.getSelectedIndex()];
        fcil = EAFDefault_EarlyDesign.fcil[fcilcombo.getSelectedIndex()];
        ruse = EAFDefault_EarlyDesign.ruse[rusecombo.getSelectedIndex()];
        System.out.println(pers+" "+rcpx+" "+pdif+" "+prex+" "+fcil+" "+ruse);
        
    }
		public void calculateEaf() {
	        netEafearly = pers * rcpx * pdif * prex * fcil * ruse;
	    }
	    
	    private void initEafLevelEarly()
	    {
	    	perscombo.setSelectedItem(this.eafRatingearly[EAF_PERS]);
	        rcpxcombo.setSelectedItem(this.eafRatingearly[EAF_RCPX]);
	        pdifcombo.setSelectedItem(this.eafRatingearly[EAF_PDIF]);
	        prexcombo.setSelectedItem(this.eafRatingearly[EAF_PREX]);
	        fcilcombo.setSelectedItem(this.eafRatingearly[EAF_FCIL]);
	        rusecombo.setSelectedItem(this.eafRatingearly[EAF_RUSE]);
	    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EAF_EarlyDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EAF_EarlyDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EAF_EarlyDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EAF_EarlyDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EAF_EarlyDesign dialog1 = new EAF_EarlyDesign(new javax.swing.JFrame(), true, null);
                dialog1.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog1.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbutton;
    private javax.swing.JButton Okbutton;
    private javax.swing.JComboBox<String> fcilcombo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> pdifcombo;
    private javax.swing.JComboBox<String> perscombo;
    private javax.swing.JComboBox<String> prexcombo;
    private javax.swing.JComboBox<String> rcpxcombo;
    private javax.swing.JComboBox<String> rusecombo;
    // End of variables declaration//GEN-END:variables
}
