/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocomoJava;

import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author shriraksharao
 */
public class EAFDefault_EarlyDesign extends javax.swing.JFrame {
    public static double[] pers  = {1.00,2.12,1.62,1.26,0.83,0.63,0.50};
    public static double[] rcpx  = {1.00,0.49,0.60,0.83,1.33,1.91,2.72};
    public static double[] pdif  = {1.00,0.87,1.29,1.81,2.61};
    public static double[] prex  = {1.00,1.59,1.33,1.12,0.87,0.74,0.62};
    public static double[] fcil  = {1.00,1.43,1.30,1.10,0.87,0.73,0.62};
    public static double[] ruse  = {1.00,0.95,1.07,1.15,1.24};
    
    
    public final double[] defpers  = {2.12,1.62,1.26,1.00,0.83,0.63,0.50};
    public final double[] defrcpx  = {0.49,0.60,0.83,1.00,1.33,1.91,2.72};
    public final double[] defpdif  = {0.87,1.00,1.29,1.81,2.61};
    public final double[] defprex  = {1.59,1.33,1.12,1.00,0.87,0.74,0.62};
    public final double[] deffcil  = {1.43,1.30,1.10,1.0,0.87,0.73,0.62};
    public final double[] defruse  = {0.95,1.00,1.07,1.15,1.24};

    /**
     * Creates new form EAFDefault_EarlyDesign
     */
    public EAFDefault_EarlyDesign() {
        initComponents();
        this.setTitle("EAF Early Design Default Values");
        this.getContentPane().setBackground(Color.white);
        persEL.setText(String.valueOf(pers[1]));
        persVL.setText(String.valueOf(pers[2]));
        persL.setText(String.valueOf(pers[3]));
        persN.setText(String.valueOf(pers[0]));
        persH.setText(String.valueOf(pers[4]));
        persVH.setText(String.valueOf(pers[5]));
        persEH.setText(String.valueOf(pers[6]));
        
        rcpxEL.setText(String.valueOf(rcpx[1]));
        rcpxVL.setText(String.valueOf(rcpx[2]));
        rcpxL.setText(String.valueOf(rcpx[3]));
        rcpxN.setText(String.valueOf(rcpx[0]));
        rcpxH.setText(String.valueOf(rcpx[4]));
        rcpxVH.setText(String.valueOf(rcpx[5]));
        rcpxEH.setText(String.valueOf(rcpx[6]));
        
        pdifL.setText(String.valueOf(pdif[1]));
        pdifN.setText(String.valueOf(pdif[0]));
        pdifH.setText(String.valueOf(pdif[2]));
        pdifVH.setText(String.valueOf(pdif[3]));
        pdifEH.setText(String.valueOf(pdif[4]));
        
        prexEL.setText(String.valueOf(prex[1]));
        prexVL.setText(String.valueOf(prex[2]));
        prexL.setText(String.valueOf(prex[3]));
        prexN.setText(String.valueOf(prex[0]));
        prexH.setText(String.valueOf(prex[4]));
        prexVH.setText(String.valueOf(prex[5]));
        prexEH.setText(String.valueOf(prex[6]));
        
        fcilEL.setText(String.valueOf(fcil[1]));
        fcilVL.setText(String.valueOf(fcil[2]));
        fcilL.setText(String.valueOf(fcil[3]));
        fcilN.setText(String.valueOf(fcil[0]));
        fcilH.setText(String.valueOf(fcil[4]));
        fcilVH.setText(String.valueOf(fcil[5]));
        fcilEH.setText(String.valueOf(fcil[6]));
        
        ruseL.setText(String.valueOf(ruse[1]));
        ruseN.setText(String.valueOf(ruse[0]));
        ruseH.setText(String.valueOf(ruse[2]));
        ruseVH.setText(String.valueOf(ruse[3]));
        ruseEH.setText(String.valueOf(ruse[4]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        persEL = new javax.swing.JTextField();
        persVL = new javax.swing.JTextField();
        persL = new javax.swing.JTextField();
        persN = new javax.swing.JTextField();
        persH = new javax.swing.JTextField();
        persVH = new javax.swing.JTextField();
        persEH = new javax.swing.JTextField();
        rcpxEL = new javax.swing.JTextField();
        rcpxVL = new javax.swing.JTextField();
        rcpxL = new javax.swing.JTextField();
        rcpxN = new javax.swing.JTextField();
        rcpxH = new javax.swing.JTextField();
        rcpxVH = new javax.swing.JTextField();
        rcpxEH = new javax.swing.JTextField();
        pdifL = new javax.swing.JTextField();
        pdifN = new javax.swing.JTextField();
        pdifH = new javax.swing.JTextField();
        pdifVH = new javax.swing.JTextField();
        pdifEH = new javax.swing.JTextField();
        prexEL = new javax.swing.JTextField();
        prexVL = new javax.swing.JTextField();
        prexL = new javax.swing.JTextField();
        prexN = new javax.swing.JTextField();
        prexH = new javax.swing.JTextField();
        prexVH = new javax.swing.JTextField();
        prexEH = new javax.swing.JTextField();
        fcilEL = new javax.swing.JTextField();
        fcilVL = new javax.swing.JTextField();
        fcilL = new javax.swing.JTextField();
        fcilN = new javax.swing.JTextField();
        fcilH = new javax.swing.JTextField();
        fcilVH = new javax.swing.JTextField();
        fcilEH = new javax.swing.JTextField();
        ruseL = new javax.swing.JTextField();
        ruseN = new javax.swing.JTextField();
        ruseH = new javax.swing.JTextField();
        ruseVH = new javax.swing.JTextField();
        ruseEH = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        okbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("PERS");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("RCPX");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("PDIF");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("PREX");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("FCIL");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("RUSE");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Extra Low");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("Very Low");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("Low");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("Nominal");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("High");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("Very High");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setText("Extra High");

        persEL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        persEL.setText("2.12");
        persEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persELActionPerformed(evt);
            }
        });

        persVL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        persVL.setText("1.62");
        persVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persVLActionPerformed(evt);
            }
        });

        persL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        persL.setText("1.26");
        persL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persLActionPerformed(evt);
            }
        });

        persN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        persN.setText("1.0");
        persN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persNActionPerformed(evt);
            }
        });

        persH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        persH.setText("0.83");
        persH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persHActionPerformed(evt);
            }
        });

        persVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        persVH.setText("0.63");
        persVH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persVHActionPerformed(evt);
            }
        });

        persEH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        persEH.setText("0.5");
        persEH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persEHActionPerformed(evt);
            }
        });

        rcpxEL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rcpxEL.setText("0.49");
        rcpxEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcpxELActionPerformed(evt);
            }
        });

        rcpxVL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rcpxVL.setText("0.6");
        rcpxVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcpxVLActionPerformed(evt);
            }
        });

        rcpxL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rcpxL.setText("0.83");
        rcpxL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcpxLActionPerformed(evt);
            }
        });

        rcpxN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rcpxN.setText("1.0");
        rcpxN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcpxNActionPerformed(evt);
            }
        });

        rcpxH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rcpxH.setText("1.33");
        rcpxH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcpxHActionPerformed(evt);
            }
        });

        rcpxVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rcpxVH.setText("1.91");
        rcpxVH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcpxVHActionPerformed(evt);
            }
        });

        rcpxEH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rcpxEH.setText("2.72");
        rcpxEH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcpxEHActionPerformed(evt);
            }
        });

        pdifL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pdifL.setText("0.87");
        pdifL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdifLActionPerformed(evt);
            }
        });

        pdifN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pdifN.setText("1.0");
        pdifN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdifNActionPerformed(evt);
            }
        });

        pdifH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pdifH.setText("1.29");
        pdifH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdifHActionPerformed(evt);
            }
        });

        pdifVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pdifVH.setText("1.81");
        pdifVH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdifVHActionPerformed(evt);
            }
        });

        pdifEH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pdifEH.setText("2.61");
        pdifEH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdifEHActionPerformed(evt);
            }
        });

        prexEL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        prexEL.setText("1.59");
        prexEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prexELActionPerformed(evt);
            }
        });

        prexVL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        prexVL.setText("1.33");
        prexVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prexVLActionPerformed(evt);
            }
        });

        prexL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        prexL.setText("1.12");
        prexL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prexLActionPerformed(evt);
            }
        });

        prexN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        prexN.setText("1.0");
        prexN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prexNActionPerformed(evt);
            }
        });

        prexH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        prexH.setText("0.87");
        prexH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prexHActionPerformed(evt);
            }
        });

        prexVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        prexVH.setText("0.74");
        prexVH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prexVHActionPerformed(evt);
            }
        });

        prexEH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        prexEH.setText("0.62");
        prexEH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prexEHActionPerformed(evt);
            }
        });

        fcilEL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        fcilEL.setText("1.43");
        fcilEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcilELActionPerformed(evt);
            }
        });

        fcilVL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        fcilVL.setText("1.3");
        fcilVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcilVLActionPerformed(evt);
            }
        });

        fcilL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        fcilL.setText("1.1");
        fcilL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcilLActionPerformed(evt);
            }
        });

        fcilN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        fcilN.setText("1.0");
        fcilN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcilNActionPerformed(evt);
            }
        });

        fcilH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        fcilH.setText("0.87");
        fcilH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcilHActionPerformed(evt);
            }
        });

        fcilVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        fcilVH.setText("0.73");
        fcilVH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcilVHActionPerformed(evt);
            }
        });

        fcilEH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        fcilEH.setText("0.62");
        fcilEH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcilEHActionPerformed(evt);
            }
        });

        ruseL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ruseL.setText("0.95");
        ruseL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruseLActionPerformed(evt);
            }
        });

        ruseN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ruseN.setText("1.0");
        ruseN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruseNActionPerformed(evt);
            }
        });

        ruseH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ruseH.setText("1.07");
        ruseH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruseHActionPerformed(evt);
            }
        });

        ruseVH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ruseVH.setText("1.15");
        ruseVH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruseVHActionPerformed(evt);
            }
        });

        ruseEH.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ruseEH.setText("1.24");
        ruseEH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruseEHActionPerformed(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(102, 204, 255));
        Reset.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        okbutton.setBackground(new java.awt.Color(102, 204, 255));
        okbutton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        okbutton.setText("OK");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rcpxEL)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(persEL)
                    .addComponent(prexEL)
                    .addComponent(fcilEL))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fcilVL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(prexVL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(persVL)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rcpxVL)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(persL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(persN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rcpxH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rcpxVH))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(persH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(persVH))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ruseL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ruseN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fcilL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fcilN))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prexL, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(pdifL)
                                    .addComponent(rcpxL))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rcpxN)
                                            .addComponent(pdifN)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(prexN)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prexH, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(pdifH)
                            .addComponent(fcilH)
                            .addComponent(ruseH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pdifVH, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(prexVH)
                            .addComponent(fcilVH)
                            .addComponent(ruseVH))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(persEH)
                    .addComponent(rcpxEH)
                    .addComponent(pdifEH)
                    .addComponent(prexEH)
                    .addComponent(fcilEH)
                    .addComponent(ruseEH))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reset)
                .addGap(111, 111, 111)
                .addComponent(okbutton)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(persEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persEH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rcpxEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcpxVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcpxL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcpxN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcpxH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcpxVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcpxEH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pdifL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pdifN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pdifH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pdifVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pdifEH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(prexEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fcilEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prexVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prexL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prexN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prexH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prexVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prexEH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fcilVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fcilL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fcilN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fcilH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fcilVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fcilEH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ruseL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ruseN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ruseH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ruseVH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ruseEH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset)
                    .addComponent(okbutton))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void persELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persELActionPerformed

    private void persVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persVLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persVLActionPerformed

    private void persLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persLActionPerformed

    private void persNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persNActionPerformed

    private void persHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persHActionPerformed

    private void persVHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persVHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persVHActionPerformed

    private void persEHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persEHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persEHActionPerformed

    private void rcpxELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcpxELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcpxELActionPerformed

    private void rcpxVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcpxVLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcpxVLActionPerformed

    private void rcpxLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcpxLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcpxLActionPerformed

    private void rcpxNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcpxNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcpxNActionPerformed

    private void rcpxHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcpxHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcpxHActionPerformed

    private void rcpxVHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcpxVHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcpxVHActionPerformed

    private void rcpxEHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcpxEHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcpxEHActionPerformed

    private void pdifLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdifLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdifLActionPerformed

    private void pdifNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdifNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdifNActionPerformed

    private void pdifHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdifHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdifHActionPerformed

    private void pdifVHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdifVHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdifVHActionPerformed

    private void pdifEHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdifEHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdifEHActionPerformed

    private void prexELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prexELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prexELActionPerformed

    private void prexVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prexVLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prexVLActionPerformed

    private void prexLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prexLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prexLActionPerformed

    private void prexNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prexNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prexNActionPerformed

    private void prexHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prexHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prexHActionPerformed

    private void ruseEHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruseEHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruseEHActionPerformed

    private void ruseVHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruseVHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruseVHActionPerformed

    private void ruseHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruseHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruseHActionPerformed

    private void ruseNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruseNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruseNActionPerformed

    private void ruseLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruseLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruseLActionPerformed

    private void fcilEHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcilEHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcilEHActionPerformed

    private void fcilVHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcilVHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcilVHActionPerformed

    private void fcilHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcilHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcilHActionPerformed

    private void fcilNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcilNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcilNActionPerformed

    private void fcilLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcilLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcilLActionPerformed

    private void fcilVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcilVLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcilVLActionPerformed

    private void fcilELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcilELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcilELActionPerformed

    private void prexEHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prexEHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prexEHActionPerformed

    private void prexVHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prexVHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prexVHActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        // TODO add your handling code here:
        	        boolean legal = true;
		        
		        legal &= validateDouble(persEL.getText());
		        legal &= validateDouble(persVL.getText());
		        legal &= validateDouble(persL.getText());
		        legal &= validateDouble(persH.getText());
		        legal &= validateDouble(persVH.getText());
		        legal &= validateDouble(persEL.getText());
		        
		        legal &= validateDouble(rcpxEL.getText());
		        legal &= validateDouble(rcpxVL.getText());
		        legal &= validateDouble(rcpxL.getText());
		        legal &= validateDouble(rcpxN.getText());
		        legal &= validateDouble(rcpxH.getText());
		        legal &= validateDouble(rcpxVH.getText());
		        legal &= validateDouble(rcpxEH.getText());
		        
		        legal &= validateDouble(pdifL.getText());
		        legal &= validateDouble(pdifN.getText());
		        legal &= validateDouble(pdifH.getText());
		        legal &= validateDouble(pdifVH.getText());
		        legal &= validateDouble(pdifEH.getText());
		        
		        legal &= validateDouble(prexEL.getText());
		        legal &= validateDouble(prexVL.getText());
		        legal &= validateDouble(prexL.getText());
		        legal &= validateDouble(prexN.getText());
		        legal &= validateDouble(prexH.getText());
		        legal &= validateDouble(prexVH.getText());
		        legal &= validateDouble(prexEH.getText());
		        
		        legal &= validateDouble(fcilEL.getText());
		        legal &= validateDouble(fcilVL.getText());
		        legal &= validateDouble(fcilL.getText());
		        legal &= validateDouble(fcilN.getText());
		        legal &= validateDouble(fcilH.getText());
		        legal &= validateDouble(fcilVH.getText());
		        legal &= validateDouble(fcilEH.getText());
		        
		        legal &= validateDouble(ruseL.getText());
		        legal &= validateDouble(ruseN.getText());
		        legal &= validateDouble(ruseVH.getText());
		        legal &= validateDouble(ruseEH.getText());
		        
		        
		        if(legal){
		            changeEAFValues();
		            this.dispose();
		        }
		        else{
		            JOptionPane.showMessageDialog(null, "Invalid Input", "Error",JOptionPane.ERROR_MESSAGE);
		        }	

    }//GEN-LAST:event_okbuttonActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
                                for(int i = 0; i < 6; ++i) pers[i] = defpers[i];
			        for(int i = 0; i < 6; ++i) rcpx[i] = defrcpx[i];
			        for(int i = 0; i < 5; ++i) pdif[i] = defpdif[i];
			        for(int i = 0; i < 6; ++i) prex[i] = defprex[i];
			        for(int i = 0; i < 6; ++i) fcil[i] = deffcil[i];
			        for(int i = 0; i < 5; ++i) ruse[i] = defruse[i];
			        
			        persEL.setText(String.valueOf(pers[1]));
			        persVL.setText(String.valueOf(pers[2]));
			        persL.setText(String.valueOf(pers[3]));
			        persN.setText(String.valueOf(pers[0]));
			        persH.setText(String.valueOf(pers[4]));
			        persVH.setText(String.valueOf(pers[5]));
			        persEH.setText(String.valueOf(pers[6]));
			        
			        rcpxEL.setText(String.valueOf(rcpx[1]));
			        rcpxVL.setText(String.valueOf(rcpx[2]));
			        rcpxL.setText(String.valueOf(rcpx[3]));
			        rcpxN.setText(String.valueOf(rcpx[0]));
			        rcpxH.setText(String.valueOf(rcpx[4]));
			        rcpxVH.setText(String.valueOf(rcpx[5]));
			        rcpxEH.setText(String.valueOf(rcpx[6]));
			        
			        pdifL.setText(String.valueOf(pdif[1]));
			        pdifN.setText(String.valueOf(pdif[0]));
			        pdifH.setText(String.valueOf(pdif[2]));
			        pdifVH.setText(String.valueOf(pdif[3]));
			        pdifEH.setText(String.valueOf(pdif[4]));
			        
			        prexEL.setText(String.valueOf(prex[1]));
			        prexVL.setText(String.valueOf(prex[2]));
			        prexL.setText(String.valueOf(prex[3]));
			        prexN.setText(String.valueOf(prex[0]));
			        prexH.setText(String.valueOf(prex[4]));
			        prexVH.setText(String.valueOf(prex[5]));
			        prexEH.setText(String.valueOf(prex[6]));
			        
			        fcilEL.setText(String.valueOf(fcil[1]));
			        fcilVL.setText(String.valueOf(fcil[2]));
			        fcilL.setText(String.valueOf(fcil[3]));
			        fcilN.setText(String.valueOf(fcil[0]));
			        fcilH.setText(String.valueOf(fcil[4]));
			        fcilVH.setText(String.valueOf(fcil[5]));
			        fcilEH.setText(String.valueOf(fcil[6]));
			        
			        ruseL.setText(String.valueOf(ruse[1]));
			        ruseN.setText(String.valueOf(ruse[0]));
			        ruseH.setText(String.valueOf(ruse[2]));
			        ruseVH.setText(String.valueOf(ruse[3]));
			        ruseEH.setText(String.valueOf(ruse[4]));
    }//GEN-LAST:event_ResetActionPerformed
      private boolean validateDouble(String s){
            String ss = s.replace(" ","");
            if(ss.length()==0) return false;
            else return Pattern.matches("^(0\\.\\d*[1-9]\\d*)|([1-9]\\d*(\\.\\d+)?)$",
				ss);
        }
      private void changeEAFValues(){
		        
		        pers[1] = Double.valueOf(persEL.getText());
		        pers[2] = Double.valueOf(persVL.getText());
		        pers[3] = Double.valueOf(persL.getText());
		        pers[0] = Double.valueOf(persN.getText());
		        pers[4] = Double.valueOf(persH.getText());
		        pers[5] = Double.valueOf(persVH.getText());
		        pers[6] = Double.valueOf(persEL.getText());
		        
		        rcpx[1] = Double.valueOf(rcpxEL.getText());
		        rcpx[2] = Double.valueOf(rcpxVL.getText());
		        rcpx[3] = Double.valueOf(rcpxL.getText());
		        rcpx[0] = Double.valueOf(rcpxN.getText());
		        rcpx[4] = Double.valueOf(rcpxH.getText());
		        rcpx[5] = Double.valueOf(rcpxVH.getText());
		        rcpx[6] = Double.valueOf(rcpxEH.getText());
		        
		        pdif[1] = Double.valueOf(pdifL.getText());
		        pdif[0] = Double.valueOf(pdifN.getText());
		        pdif[2] = Double.valueOf(pdifH.getText());
		        pdif[3] = Double.valueOf(pdifVH.getText());
		        pdif[4] = Double.valueOf(pdifEH.getText());
		        
		        prex[1] = Double.valueOf(prexEL.getText());
		        prex[2] = Double.valueOf(prexVL.getText());
		        prex[3] = Double.valueOf(prexL.getText());
		        prex[0] = Double.valueOf(prexN.getText());
		        prex[4] = Double.valueOf(prexH.getText());
		        prex[5] = Double.valueOf(prexVH.getText());
		        prex[6] = Double.valueOf(prexEH.getText());
		        
		        fcil[1] = Double.valueOf(fcilL.getText());
		        fcil[0] = Double.valueOf(fcilN.getText());
		        fcil[2] = Double.valueOf(fcilH.getText());
		        fcil[3] = Double.valueOf(fcilVH.getText());
		        fcil[4] = Double.valueOf(fcilEH.getText());
		        
                        ruse[1] = Double.valueOf(ruseL.getText());
		        ruse[0] = Double.valueOf(ruseN.getText());
		        ruse[2] = Double.valueOf(ruseH.getText());
		        ruse[3] = Double.valueOf(ruseVH.getText());
		        ruse[4] = Double.valueOf(ruseEH.getText());  
		    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EAFDefault_EarlyDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EAFDefault_EarlyDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EAFDefault_EarlyDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EAFDefault_EarlyDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EAFDefault_EarlyDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JTextField fcilEH;
    private javax.swing.JTextField fcilEL;
    private javax.swing.JTextField fcilH;
    private javax.swing.JTextField fcilL;
    private javax.swing.JTextField fcilN;
    private javax.swing.JTextField fcilVH;
    private javax.swing.JTextField fcilVL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton okbutton;
    private javax.swing.JTextField pdifEH;
    private javax.swing.JTextField pdifH;
    private javax.swing.JTextField pdifL;
    private javax.swing.JTextField pdifN;
    private javax.swing.JTextField pdifVH;
    private javax.swing.JTextField persEH;
    private javax.swing.JTextField persEL;
    private javax.swing.JTextField persH;
    private javax.swing.JTextField persL;
    private javax.swing.JTextField persN;
    private javax.swing.JTextField persVH;
    private javax.swing.JTextField persVL;
    private javax.swing.JTextField prexEH;
    private javax.swing.JTextField prexEL;
    private javax.swing.JTextField prexH;
    private javax.swing.JTextField prexL;
    private javax.swing.JTextField prexN;
    private javax.swing.JTextField prexVH;
    private javax.swing.JTextField prexVL;
    private javax.swing.JTextField rcpxEH;
    private javax.swing.JTextField rcpxEL;
    private javax.swing.JTextField rcpxH;
    private javax.swing.JTextField rcpxL;
    private javax.swing.JTextField rcpxN;
    private javax.swing.JTextField rcpxVH;
    private javax.swing.JTextField rcpxVL;
    private javax.swing.JTextField ruseEH;
    private javax.swing.JTextField ruseH;
    private javax.swing.JTextField ruseL;
    private javax.swing.JTextField ruseN;
    private javax.swing.JTextField ruseVH;
    // End of variables declaration//GEN-END:variables

}
