/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocomoJava;

import java.awt.Desktop;
import java.awt.Frame;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shriraksharao
 */
public class Maintenance_Module extends javax.swing.JFrame {

    public DefaultTableModel model1;
    public ArrayList<Object> modulename = new ArrayList<Object>();
    public ArrayList<String> moduledata = new ArrayList<String>();
    public double sf;
    public double[] devsloc = new double[10];
    public double[] dev_pm = new double[10];
    public double[] dev_cost = new double[10];
    public String[] modname = new String[10];
    public String mod_name;
    public  ArrayList<String> arr_list = new ArrayList<String>(10);
/**
     * Creates new form Maintenance_Module
     */
        final int TABLE_COL_COUNT    = 13;
        CocomoDashboard cocoDash_maintenance;
        public Maintenance_Module(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        initComponents();
        cocoDash_maintenance = (CocomoDashboard) parent;
        this.model1 = (DefaultTableModel) module.getModel();
        model1.setRowCount(0);
        
        modulename =this.cocoDash_maintenance.getmodulename();
        moduledata = this.cocoDash_maintenance.getmoduledata();
        for(int i=0;i<this.cocoDash_maintenance.ct;i++)
        {
          model1.addRow(new Object[]{((Object[])modulename.get(i))[1]});
          modname[i] = String.valueOf(((Object[])modulename.get(i))[1]);
          
        }
        for(int i=0;i<this.cocoDash_maintenance.ct;i++)
        {
          devsloc[i] = Double.valueOf((moduledata.get(i*3)));
          dev_pm[i]  = Double.valueOf(moduledata.get(i*3+1));
          dev_cost[i] = Double.valueOf(moduledata.get(i*3+2)); 
        }
        
        sf = Float.valueOf(cocoDash_maintenance.netScaleFactor.getText());         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ok_button = new javax.swing.JButton();
        Cancel_button = new javax.swing.JButton();
        Help_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        module = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Module Maintenance");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setText("Module List");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Module Selected");

        Ok_button.setBackground(new java.awt.Color(102, 204, 255));
        Ok_button.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Ok_button.setText("OK");
        Ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ok_buttonActionPerformed(evt);
            }
        });

        Cancel_button.setBackground(new java.awt.Color(102, 204, 255));
        Cancel_button.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Cancel_button.setText("Cancel");
        Cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_buttonActionPerformed(evt);
            }
        });

        Help_button.setBackground(new java.awt.Color(102, 204, 255));
        Help_button.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Help_button.setText("Help");
        Help_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Default Module");

        module.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        module.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Select One Module"
            }
        ));
        module.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moduleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(module);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Ok_button)
                        .addGap(32, 32, 32)
                        .addComponent(Cancel_button)
                        .addGap(39, 39, 39)
                        .addComponent(Help_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ok_button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cancel_button)
                        .addComponent(Help_button)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ok_buttonActionPerformed
        // TODO add your handling code here:
        Maintenance_Mod_secondpage sp =new Maintenance_Mod_secondpage(this,true);
        sp.setVisible(true);
        sp.setAlwaysOnTop(true); 
        
    }//GEN-LAST:event_Ok_buttonActionPerformed

    private void Cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Cancel_buttonActionPerformed

    private void Help_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_buttonActionPerformed
        // TODO add your handling code here:
        if(Desktop.isDesktopSupported()) {
            try {
                try {
                    Desktop.getDesktop().browse(new URL("http://csse.usc.edu/csse/affiliate/private/COCOMOII_Driver+Calc_Ss/Manual-PostArch2000.pdf").toURI());
                } catch (IOException ex) {
                    Logger.getLogger(CocomoDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (URISyntaxException ex) {
                Logger.getLogger(CocomoDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            
         
        }
        else {
            JOptionPane.showMessageDialog(null, "Can't open pdf file");
        }
    }//GEN-LAST:event_Help_buttonActionPerformed

    public ArrayList<String> getdetails()
    {
        int index=0;
        while(index<=module.getSelectedRow()){
            arr_list.add(index*4,modname[index]);
            arr_list.add(index*4+1,String.valueOf(devsloc[index]));
            arr_list.add(index*4+2,String.valueOf(dev_pm[index]));
            arr_list.add(index*4+3,String.valueOf(dev_cost[index]));
        index++;
        }
        return arr_list;
    }
    private void moduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moduleMouseClicked

        if(module.getSelectedRow() != -1)
        {
            jLabel3.setText((String) ((Object[])modulename.get(module.getSelectedRow()))[1]);
        }
        
    }//GEN-LAST:event_moduleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maintenance_Module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maintenance_Module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maintenance_Module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maintenance_Module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maintenance_Module(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_button;
    private javax.swing.JButton Help_button;
    private javax.swing.JButton Ok_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable module;
    // End of variables declaration//GEN-END:variables

    
}
